### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-discordapp-module#2]
At the moment the module is broken and needs to be updated badly which will be done at some point in time.
### Bugs
- [x] Fix back-end URL to front end render issues #10

**Comment by WebCrew** [comment]
I think You used the Adspanel for the sidebar view right? And the Basic Chat because of the backend settings? Thats a good idea, I also puzzle my Modules that way, because I`m not advanced ebough with Yii and thats the only way for me to generate Modules.

Maybe this will help You: https://github.com/WebCrew/humhub-module-example
There are a lot of documentations, also in the code.

**Comment by Felli** [comment]
Well this one is going to be somewhat of a challenge because Discord runs on NodeJs and dependencies will be missing, so I have to somehow create a work around.

**Comment by WebCrew** [comment]
You dont have to do a NodeJS work around, You only have to do the Module in a bit a other way and easier :)

Do a module in which one could paste the **Discord Widget Code.** 

At the Discord Chat You can find in the **Server-Settings** the Link to **Widgets**. Here You can generate a **ready made Widget code**. 

So it is enough if You do a Module in the HH admin backend where peoples can integrate that code and You do not need NodeJS for it because it is only a **iframe** code or a **json** code snippet. Thats all :)

So You have already the parts of my Adspanel - so a place where the Discord Widget can show up. You only have to do a little work around to place the Dscord Widget code in HH admin Panel.

**Comment by Felli** [comment]
I didn't add that part of the Adspanel, tho I'm going to be rewriting the whole module offline then uploading it here. :)

**Comment by WebCrew** [comment]
Ok, but thats more work - I know You want do it by Yourself and I think You are to proud to make use of the basic of the Adspanel even if the only way You can write a HumHub sidepanel code is the same as the one in the Adspanel. 

So "rewriting the whole module" is only double of work for You Sarah, because there is only one way to add a sidepanel widget to HumHub and thats the one I was unsing in the Adspanel and it is the same part of code in all other HH modules which are in need of a sidepanel. 

Hey and to be honest with You - I have also not written the code by myself to 100% - I used Peters Adsence Module as a base :) So in short, what I want say is - I`m not a little bit better or more worse as You with writing YII or PHP, we are both beginners with it, so why we should not use parts of code of each other. Do You understand what I want say?

But so or so, I wish You good luck and much success. If I can help let me know it pls.

**Comment by Felli** [comment]
If you wish to create a pull request on some issues I pointed out, I'm more than willing to have the help, as for what I meant by that post above is I hadn't though of using that part yet, I just never got around to doing that. :laughing:

**Comment by WebCrew** [comment]
@Felli  - I did a Discord Connect Module for HumHub. Its different to the module you try to create, but you can use my module as starting point. You can use 90% of it.

You only have to extend the assets.php and integrate your needed JS and CSS files
and you have to input your own code in widgets/views/discordframe.php line 11

then you have to open every single file and replace the name **discord** with your **discordapp** or **Discord** with **Discordapp** and then your module should work :+1: 

You need maybe 20 minutes to finish it :)

**Comment by Felli** [comment]
Finished!
