### ISSUE TITLE
Make this work in PHP 7.2

### ISSUE THREAD

**Issue by nemesis567** [GreenMeteor/humhub-discordapp-module#28]
Replace class Events extends \yii\base\Object in Events.php with 
class Events extends \yii\base\BaseObject

The humhub repo is missing this change.

**Comment by Felli** [comment]
This module already supports PHP 7.2, the version within the marketplace isn't being updated at this time because the dev team of HumHub is working on an open marketplace, so I'll be closing this for the time being, if you download the latest version from the [releases](https://github.com/GreenMeteor/humhub-discordapp-module/releases/latest) you'll be able to upload and unzip it for PHP 7.2 support.

> Note: This version is for HumHub 1.3.x or newer.
